# .github/workflows/psx_scraper.yml

name: PSX Market Data Scraper

on:
  schedule:
    # Runs the workflow every 15 minutes
    - cron: '*/15  * * *'
  workflow_dispatch:

jobs:
  scrape-and-upload:
    runs-on: ubuntu-latest
    
    env:
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install chromium

      - name: Run the scraper and update Google Sheet
        run: python scrape.py